language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8-dev'
  - 'pypy3'

install:
  - pip install .
  - pip install docutils pygments

script:
  - python setup.py check --strict --metadata --restructuredtext
  - python setup.py test

deploy:
  on:
    python: '3.7'
    tags: true
  provider: pypi
  user: phx
  password:
    secure: pOiPwDCr2f9dyhDMGhQ+RzoXsW8ASX1qxwu3SCRYh7TmEO//cb/ngkov2OEgupVnJetyd/47+pPrrKqtwE5ialtFpJtYoiaNzTMzZDlaPXpNtDglBhHzv09wAsqOLflTSwvExAieOABWKW0FNuVNnJ2VQdGc2yO2F8H6T31mGXvD1JL++6k760SUEIOfXtW4nqZfJ6XOQWNlnqGB/fwrarNJYtVXrLfPEp0iQdanDPmpe64gpMHi9CJ6NUr4cVZYgrMlPCRYUdCqiaQel/y74yae73xu3//2392U8qk8eEsnaFThOLtZd+gNHbYuM49W4CgS7COMBBfIFNicQqEjoH9D/HdtXS2q9/mzequuUjhs/Cj5+hT2ydc2UJ5xkr4nlD0tNAezYNStoORwiYig3+J7cn0IfUPY+AAyP6aXAEw56uOP05lVFNq/sdIIrF6+LxOiIpQcA083P38V9NsEX+uqPGgtCRvul8A2mem/qzJAxCqgqWwyiHS7s5/fUkS0ZyFc1Vp2jzyGCrgRO7KblRC97eF8iGdwOD33B9y4HVJo+eD6el3im875+te9ieTSDrg3JedGIVb/oUa9xccM2599J3eRIixRywXkOKo6YlqmpWhy1vLmq8JSZtX2mfiRKMsQXA3wljZyIBSm7kpnVbgNnlwMnZSUFPB0NPIG4rM=
  distributions: bdist_wheel sdist
